openapi: 3.0.0
info:
  description: OpenAPI definition for TraceTest endpoint and resources
  title: TraceTest
  version: 0.0.1
servers:
- url: /api
paths:
  /tests:
    get:
      description: get tests
      operationId: getTests
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Test'
                type: array
          description: successful operation
        "500":
          description: problem with creating test
      summary: Create new test
      tags:
      - api
    post:
      description: Create new test action
      operationId: createTest
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Test'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Test'
          description: successful operation
        "500":
          description: problem with creating test
      summary: Create new test
      tags:
      - api
  /tests/{testid}:
    get:
      description: get test
      operationId: getTest
      parameters:
      - explode: false
        in: path
        name: testid
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Test'
          description: successful operation
        "500":
          description: problem with creating test
      summary: get test
      tags:
      - api
  /tests/{testid}/run:
    post:
      parameters:
      - explode: false
        in: path
        name: testid
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestRun'
          description: successful operation
      tags:
      - api
  /tests/{testid}/results/{id}:
    get:
      parameters:
      - explode: false
        in: path
        name: testid
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Result'
                type: array
          description: successful operation
      tags:
      - api
  /tests/{testid}/results/{id}/trace:
    get:
      parameters:
      - explode: false
        in: path
        name: testid
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
          description: trace
      tags:
      - api
  /tests/{id}/results:
    get:
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Result'
                type: array
          description: successful operation
      tags:
      - api
  /tests/{id}/assertions:
    get:
      description: Gets all assertions associated to the test
      operationId: getAssertions
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Assertion'
                type: array
          description: successful operation
      tags:
      - api
    post:
      operationId: createAssertion
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Assertion'
      responses:
        "200":
          description: OK
      tags:
      - api
components:
  schemas:
    Test:
      example:
        name: name
        description: description
        id: id
        assertions:
        - id: id
          selectors:
          - locationName: RESOURCE_ATTRIBUTES
            propertyName: propertyName
            valueType: stringValue
            value: value
          - locationName: RESOURCE_ATTRIBUTES
            propertyName: propertyName
            valueType: stringValue
            value: value
          spanAssertions:
          - locationName: RESOURCE_ATTRIBUTES
            propertyName: propertyName
            comparisonValue: comparisonValue
            valueType: stringValue
            operator: EQUALS
          - locationName: RESOURCE_ATTRIBUTES
            propertyName: propertyName
            comparisonValue: comparisonValue
            valueType: stringValue
            operator: EQUALS
          successful: true
        - id: id
          selectors:
          - locationName: RESOURCE_ATTRIBUTES
            propertyName: propertyName
            valueType: stringValue
            value: value
          - locationName: RESOURCE_ATTRIBUTES
            propertyName: propertyName
            valueType: stringValue
            value: value
          spanAssertions:
          - locationName: RESOURCE_ATTRIBUTES
            propertyName: propertyName
            comparisonValue: comparisonValue
            valueType: stringValue
            operator: EQUALS
          - locationName: RESOURCE_ATTRIBUTES
            propertyName: propertyName
            comparisonValue: comparisonValue
            valueType: stringValue
            operator: EQUALS
          successful: true
        serviceUnderTest:
          auth: auth
          id: id
          url: url
        lastTestResult:
          traceid: traceid
          spanid: spanid
          createdAt: 2000-01-23T04:56:07.000+00:00
          completedAt: 2000-01-23T04:56:07.000+00:00
          trace: '{}'
          response: '{}'
          testid: testid
          id: id
          failed:
            id: id
            selectors:
            - locationName: RESOURCE_ATTRIBUTES
              propertyName: propertyName
              valueType: stringValue
              value: value
            - locationName: RESOURCE_ATTRIBUTES
              propertyName: propertyName
              valueType: stringValue
              value: value
            spanAssertions:
            - locationName: RESOURCE_ATTRIBUTES
              propertyName: propertyName
              comparisonValue: comparisonValue
              valueType: stringValue
              operator: EQUALS
            - locationName: RESOURCE_ATTRIBUTES
              propertyName: propertyName
              comparisonValue: comparisonValue
              valueType: stringValue
              operator: EQUALS
            successful: true
          successful:
            id: id
            selectors:
            - locationName: RESOURCE_ATTRIBUTES
              propertyName: propertyName
              valueType: stringValue
              value: value
            - locationName: RESOURCE_ATTRIBUTES
              propertyName: propertyName
              valueType: stringValue
              value: value
            spanAssertions:
            - locationName: RESOURCE_ATTRIBUTES
              propertyName: propertyName
              comparisonValue: comparisonValue
              valueType: stringValue
              operator: EQUALS
            - locationName: RESOURCE_ATTRIBUTES
              propertyName: propertyName
              comparisonValue: comparisonValue
              valueType: stringValue
              operator: EQUALS
            successful: true
      properties:
        id:
          description: ID
          readOnly: true
          type: string
        name:
          type: string
        description:
          type: string
        serviceUnderTest:
          $ref: '#/components/schemas/Test_serviceUnderTest'
        assertions:
          description: Definition of assertions that are going to be made
          items:
            $ref: '#/components/schemas/Assertion'
          type: array
        lastTestResult:
          $ref: '#/components/schemas/Result'
      type: object
    Assertion:
      example:
        id: id
        selectors:
        - locationName: RESOURCE_ATTRIBUTES
          propertyName: propertyName
          valueType: stringValue
          value: value
        - locationName: RESOURCE_ATTRIBUTES
          propertyName: propertyName
          valueType: stringValue
          value: value
        spanAssertions:
        - locationName: RESOURCE_ATTRIBUTES
          propertyName: propertyName
          comparisonValue: comparisonValue
          valueType: stringValue
          operator: EQUALS
        - locationName: RESOURCE_ATTRIBUTES
          propertyName: propertyName
          comparisonValue: comparisonValue
          valueType: stringValue
          operator: EQUALS
        successful: true
      properties:
        id:
          description: ID
          readOnly: true
          type: string
        selectors:
          items:
            $ref: '#/components/schemas/SelectorItem'
          type: array
        spanAssertions:
          items:
            $ref: '#/components/schemas/SpanAssertion'
          type: array
        successful:
          type: boolean
      type: object
    Result:
      example:
        traceid: traceid
        spanid: spanid
        createdAt: 2000-01-23T04:56:07.000+00:00
        completedAt: 2000-01-23T04:56:07.000+00:00
        trace: '{}'
        response: '{}'
        testid: testid
        id: id
        failed:
          id: id
          selectors:
          - locationName: RESOURCE_ATTRIBUTES
            propertyName: propertyName
            valueType: stringValue
            value: value
          - locationName: RESOURCE_ATTRIBUTES
            propertyName: propertyName
            valueType: stringValue
            value: value
          spanAssertions:
          - locationName: RESOURCE_ATTRIBUTES
            propertyName: propertyName
            comparisonValue: comparisonValue
            valueType: stringValue
            operator: EQUALS
          - locationName: RESOURCE_ATTRIBUTES
            propertyName: propertyName
            comparisonValue: comparisonValue
            valueType: stringValue
            operator: EQUALS
          successful: true
        successful:
          id: id
          selectors:
          - locationName: RESOURCE_ATTRIBUTES
            propertyName: propertyName
            valueType: stringValue
            value: value
          - locationName: RESOURCE_ATTRIBUTES
            propertyName: propertyName
            valueType: stringValue
            value: value
          spanAssertions:
          - locationName: RESOURCE_ATTRIBUTES
            propertyName: propertyName
            comparisonValue: comparisonValue
            valueType: stringValue
            operator: EQUALS
          - locationName: RESOURCE_ATTRIBUTES
            propertyName: propertyName
            comparisonValue: comparisonValue
            valueType: stringValue
            operator: EQUALS
          successful: true
      properties:
        id:
          description: ID
          readOnly: true
          type: string
        testid:
          description: test ID
          readOnly: true
          type: string
        traceid:
          description: trace ID
          readOnly: true
          type: string
        spanid:
          description: parent span ID
          readOnly: true
          type: string
        successful:
          $ref: '#/components/schemas/Assertion'
        failed:
          $ref: '#/components/schemas/Assertion'
        createdAt:
          format: date-time
          type: string
        completedAt:
          format: date-time
          type: string
        response:
          description: TODO(pov) This is going to be HTTP Response object for now,
            at some point it might be GRPC/SOAP/...
          type: object
        trace:
          description: Trace in standard OTEL format, only set when getting single
            test result
          type: object
      type: object
    Attribute:
      properties:
        id:
          description: ID
          readOnly: true
          type: string
        key:
          type: string
        value:
          type: string
      type: object
    TestRun:
      example:
        id: id
      properties:
        id:
          description: ID
          readOnly: true
          type: string
      type: object
    SelectorItem:
      example:
        locationName: RESOURCE_ATTRIBUTES
        propertyName: propertyName
        valueType: stringValue
        value: value
      properties:
        locationName:
          description: Example "SPAN"
          enum:
          - RESOURCE_ATTRIBUTES
          - INSTRUMENTATION_LIBRARY
          - SPAN
          - SPAN_ATTRIBUTES
          type: string
        propertyName:
          description: Example "operation"
          type: string
        value:
          description: Example "POST /users/verify"
          type: string
        valueType:
          description: TODO(pov) think about value types?
          enum:
          - stringValue
          - intValue
          type: string
      type: object
    SpanAssertion:
      example:
        locationName: RESOURCE_ATTRIBUTES
        propertyName: propertyName
        comparisonValue: comparisonValue
        valueType: stringValue
        operator: EQUALS
      properties:
        locationName:
          description: Example "SPAN_ATTRIBUTES"
          enum:
          - RESOURCE_ATTRIBUTES
          - INSTRUMENTATION_LIBRARY
          - SPAN
          - SPAN_ATTRIBUTES
          type: string
        propertyName:
          description: Example "http.status.code"
          type: string
        valueType:
          description: Example "intValue"
          enum:
          - stringValue
          - intValue
          type: string
        operator:
          description: Example "EQUALS"
          enum:
          - EQUALS
          - LESSTHAN
          - GREATERTHAN
          - NOTEQUALS
          type: string
        comparisonValue:
          description: Example "200"
          type: string
      type: object
    Test_serviceUnderTest:
      description: TODO(pov) Postman collections format for Requests
      example:
        auth: auth
        id: id
        url: url
      properties:
        id:
          description: ID
          readOnly: true
          type: string
        url:
          description: URL of the service under test
          type: string
        auth:
          description: authorization data for the request
          type: string
      type: object
